spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pranit-yawalkar/cloud-config-server

server:
  port: 9004


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
